# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  BINARY_NAME: gh-mcp
  COVERAGE_FILE: coverage.out
  BIN_DIR: bin
  GOLANGCI_LINT_VERSION: v2.9.0

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  bundled:prepare:
    desc: Download and verify bundled github-mcp-server archives
    vars:
      MCP_SERVER_VERSION:
        sh: 'sed -nE ''s/^const mcpServerVersion = "(v[^"]+)"$/\1/p'' mcp_version.go | sed ''s/^v//'''
    status:
      - |
        checksums_file="bundled/github-mcp-server_{{.MCP_SERVER_VERSION}}_checksums.txt"
        test -f "${checksums_file}" || exit 1

        sha256_file() {
          file_path="$1"
          if command -v shasum >/dev/null 2>&1; then
            shasum -a 256 "${file_path}" | awk '{print $1}'
            return
          fi
          if command -v sha256sum >/dev/null 2>&1; then
            sha256sum "${file_path}" | awk '{print $1}'
            return
          fi
          return 1
        }

        for asset in \
          github-mcp-server_Darwin_arm64.tar.gz \
          github-mcp-server_Darwin_x86_64.tar.gz \
          github-mcp-server_Linux_i386.tar.gz \
          github-mcp-server_Linux_arm64.tar.gz \
          github-mcp-server_Linux_x86_64.tar.gz \
          github-mcp-server_Windows_arm64.zip \
          github-mcp-server_Windows_i386.zip \
          github-mcp-server_Windows_x86_64.zip; do
          file_path="bundled/${asset}"
          test -f "${file_path}" || exit 1
          expected="$(awk -v file_name="${asset}" '$2==file_name {print $1; exit}' "${checksums_file}")"
          test -n "${expected}" || exit 1
          actual="$(sha256_file "${file_path}")" || exit 1
          test "${actual}" = "${expected}" || exit 1
        done
    cmds:
      - ./scripts/prepare-bundled-mcp-server.sh

  build:
    desc: Build the binary
    deps: [bundled:prepare]
    sources:
      - "**/*.go"
      - "bundled/*"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY_NAME}}"
    cmds:
      - go build -o {{.BINARY_NAME}} .

  install:
    desc: Install gh-mcp as a GitHub CLI extension
    deps: [build]
    cmds:
      - gh extension install .

  uninstall:
    desc: Uninstall gh-mcp extension
    cmds:
      - gh extension remove mcp

  clean:
    desc: Remove build artifacts and coverage files
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -f {{.COVERAGE_FILE}} coverage.html
      - rm -f bundled/github-mcp-server_*
      - go clean

  run:
    desc: Build and run the extension
    deps: [build]
    cmds:
      - ./{{.BINARY_NAME}}

  test:
    desc: Run tests with race detection and shuffle (10 times)
    deps: [bundled:prepare]
    cmds:
      - go test -race -shuffle=on -count=10 ./...

  test:coverage:
    desc: Run tests with coverage report
    deps: [bundled:prepare]
    preconditions:
      - sh: command -v octocov
        msg: "octocov is not installed. Please install it first."
    cmds:
      - go test -race -coverprofile={{.COVERAGE_FILE}} ./...
      - octocov ls-files

  test:verbose:
    desc: Run tests with verbose output
    deps: [bundled:prepare]
    cmds:
      - go test -v -race ./...

  install:golangci-lint:
    desc: Install golangci-lint
    vars:
      CURRENT_VERSION:
        sh: '{{.BIN_DIR}}/golangci-lint version 2>/dev/null | grep -oE "[0-9]+\.[0-9]+\.[0-9]+" | sed -n "1p" || echo ""'
    status:
      - test -f {{.BIN_DIR}}/golangci-lint
      - test "v{{.CURRENT_VERSION}}" = "{{.GOLANGCI_LINT_VERSION}}"
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b {{.BIN_DIR}} {{.GOLANGCI_LINT_VERSION}}

  lint:
    desc: Run golangci-lint
    deps:
      - task: install:golangci-lint
        silent: true
      - task: bundled:prepare
    cmds:
      - cmd: "{{.BIN_DIR}}/golangci-lint version"
        silent: true
      - "{{.BIN_DIR}}/golangci-lint run"

  fmt:
    desc: Format code using golangci-lint
    deps:
      - task: install:golangci-lint
        silent: true
    cmds:
      - cmd: "{{.BIN_DIR}}/golangci-lint version"
        silent: true
      - "{{.BIN_DIR}}/golangci-lint fmt"

  check:
    desc: Run all checks (test, lint, build)
    cmds:
      - task: lint
      - task: build
      - task: test

  deps-verify:
    desc: Verify dependencies are correct
    cmds:
      - go mod verify
